

// ARRAY DONDE SE GUARDAN LOS PRODUCTOS
const my_productos = [];

// ARRAY DONDE SE GUARDAN TODOS LOS MODELOS DE LOS PRODUCTOS
const my_modelos = [];


// ARRAY DEL CARRITO DE COMPRAS
let carrito_compras = []

// VARIABLE PARA LA CREACION DE LOS ID DE LOS PRODUCTOS
let product_id = 0

// VARIABLE PARA LA CREACION DE LOS ID DE LOS MODELOS
let modelo_id = 0

// VARIABLE DE CANTIDAD MAX DE PRODUCTOS POR PAGINA
const len = 6

